### ISSUE TITLE
Rails 4 Autocomplete undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by henriquesacramento** [sistemacode/code#12]
```
undefined method `id' for nil:NilClass
```

O Método do rails4-autocomplete retorna esse erro, mesmo na versão 4.2 do rails.
O Ideal seria remover essa Gem e criar essa funcionalidade.

**Comment by luizpicolo** [comment]
Eu havia corrigido esse [#bug](https://github.com/sistemacode/code/pull/10/files#diff-040fe691af099d5a204299ca54abbcf1R25 ), porém vou analisar este erro com mais cuidado.

**Comment by henriquesacramento** [comment]
Acha mesmo necessário a utilização desta gem?

**Comment by luizpicolo** [comment]
Digamos que ela facilita muito o uso do AutoComplete, contudo, é somente uma facilitadora o que importa mesmo é a funcionalidade :smiley:

**Comment by luizpicolo** [comment]
Fixed #15
