### ISSUE TITLE
Criação de um container Docker  (Creating a Docker container)

### ISSUE THREAD

**Issue by luizpicolo** [sistemacode/code#22]
A ideia é criar um container Docker com o Sistema CODE já instalado e configurado para facilitar o uso. Além da instalação normal, o novo usuário poderá instalar o CODE via Docker e ter um ambiente funcional que ocasione a simplificação dos passos e maximização do uso.

The idea is to create a Docker container with CODE system already installed and configured for ease of use. Besides the normal installation, the new user can install CODE via Docker and have a working environment that causes the simplification of steps and maximizing use.

**Comment by arthurmde** [comment]
@luizpicolo vou fazer esse =)

**Comment by luizpicolo** [comment]
Close #23
