### ISSUE TITLE
Adicionar Licença para uso livre do sistema 

### ISSUE THREAD

**Issue by luizpicolo** [sistemacode/code#39]
Seguindo as boas práticas prescritas pela Free Software Foundation para o uso de uma licença livre, seria interessante fazer a "adição de dois elementos em cada arquivo fonte [...]: um aviso de copyright [...], e uma declaração que permite a cópia, dizendo que o programa é distribuído sobre os termos [...]" da [licença The MIT License (MIT)](https://github.com/sistemacode/code/blob/master/LICENSE.txt), deixando claro para os usuários que o software pode ser usado da forma que ele desejar.

Fonte: https://www.gnu.org/licenses/gpl-howto.pt-br.html

**Comment by gabrielssilva** [comment]
@luizpicolo,

adicionei o license notice indicado no texto da licença MIT em cada arquivo .rb.
Enviei o patch, mas caso você queira alterar o texto, eu fiz o seguinte:

* Criei um arquivo base.rb contendo o conteúdo a ser inserido no começo de cada arquivo
* Executei o seguinte comando para inserir o conteúdo. A lógica é (1) encontrar cada arquivo .rb com o AG (find ou similar também serviriam), (2) concatenar os conteúdos para um arquivo temporário e (3) renomear o arquivo para o nome original. 

```
$ for f in $(ag -g ".rb$"); do cat base.rb $f >> f.tmp && mv f.tmp $f; done
```

Talvez seja possível fazer isso com o `sed`, mas minhas habilidades de shell param por aí. :)

!58
