### ISSUE TITLE
IncidentsController sem alertas para o usuário

### ISSUE THREAD

**Issue by brunoao86** [sistemacode/code#43]
Nenhuma mensagem de alerta está sendo exibida ao usuário quando uma ocorrência é cadastrada/editada/excluída.

![incident_without_alerts](https://cloud.githubusercontent.com/assets/14297526/19619486/822ffe82-9847-11e6-9129-2f82a65eccdd.png)

**Comment by brunoao86** [comment]
Salve, @luizpicolo! Beleza?

Já estou com a implementação que resolve essa *issue* bem encaminhada aqui. Só não consigo abrir o PR agora porque a base da implementação é o PR de refactor de alerts que está aberto.

Qualquer coisa, só falar!

Abraço!

**Comment by luizpicolo** [comment]
Salve @brunoao86. Mergiado.
