### ISSUE TITLE
Erro na tradução da paginação "truncate"

### ISSUE THREAD

**Issue by luizpicolo** [sistemacode/code#48]
Ao atingir um certo número de cadastro aparece a palavra truncate na paginação

![captura de tela de 2016-10-24 23-21-17](https://cloud.githubusercontent.com/assets/1373275/19670798/a5c37b6c-9a40-11e6-85b6-6b56ff2dbe0c.png)

**Comment by d2bit** [comment]
I'm on it... 🙃

**Comment by luizpicolo** [comment]
:tada:
