### ISSUE TITLE
DatePicket (calendário) não aparece ao selecionar o campo data

### ISSUE THREAD

**Issue by luizpicolo** [sistemacode/code#49]
DatePicket (calendário) não aparece ao selecionar o campo data. Seria interessante ser exibido o calendário como também a mascará para a digitação do conteúdo. 

![captura de tela de 2016-10-24 23-24-43](https://cloud.githubusercontent.com/assets/1373275/19670901/5a2dd44e-9a41-11e6-8fc4-b63f6dab49d9.png)

![captura de tela de 2016-10-24 23-25-07](https://cloud.githubusercontent.com/assets/1373275/19670902/5a35eb98-9a41-11e6-8fd1-c5a75bb7382d.png)

![captura de tela de 2016-10-24 23-25-23](https://cloud.githubusercontent.com/assets/1373275/19670903/5a3af73c-9a41-11e6-8ec4-2c74c0a09fa5.png)

**Comment by d2bit** [comment]
I'll do it 🙃
