### ISSUE TITLE
Upgrade Ruby Version to Last Stable

### ISSUE THREAD

**Issue by henriquesacramento** [sistemacode/code#9]
Upgrade Ruby Version to Last Stable 2.3.1

**Comment by henriquesacramento** [comment]
@luizpicolo A suite de testes funcionava ou alguns testes quebravam?

**Comment by luizpicolo** [comment]
@henriquesacramento  acabo de criar um PR #10 para este bug. Aguardando o status ficar OK para o merge.

**Comment by henriquesacramento** [comment]
Eu estava corrigindo parte dos specs, estava já quase 90%

**Comment by luizpicolo** [comment]
Menos trabalho para você. :smile:

**Comment by henriquesacramento** [comment]
Assim que mergiar vou comparar com os meus testes aqui.

**Comment by luizpicolo** [comment]
Corrigido #10 . Adicionei o Travis-ci para garantir a execução 100% dos testes também.

**Comment by henriquesacramento** [comment]
@luizpicolo Não consigo subir novas branchs.

**Comment by luizpicolo** [comment]
Cara, se você esta trabalhando em seu Forke, isso não seria um problema.
